<a href="https://colab.research.google.com/github/ifrah123781/DecodeLabs-Project-3-SQL-Data-Analysis/blob/main/DecodeLabs_Project__3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step # 1: Import Libraries

In [1]:
import pandas as pd
import sqlite3

Step # 2: Load Dataset & Connect To SQL Database

In [6]:
from google.colab import files

uploaded = files.upload()


# load excel file
df = pd.read_excel("Dataset for Data Analytics (2).xlsx")

# connect SQLite in-memory database
conn = sqlite3.connect(":memory:")

# create SQL table
df.to_sql("orders", conn, index=False, if_exists="replace")
print("Table 'orders' successfully created with", len(df), "rows.")

Saving Dataset for Data Analytics (2).xlsx to Dataset for Data Analytics (2) (1).xlsx
Table 'orders' successfully created with 1200 rows.

Step # 3: Preview Data (Basic Select & Limit)

In [9]:
query_1 = """
SELECT OrderID, Date, CustomerID, Product, Quantity, UnitPrice, TotalPrice
FROM orders
LIMIT 5;
"""

pd.read_sql_query(query_1, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,2504.04

Step # 4: Overall Business Summary (Count, Sum, Avg)

In [10]:
query_2 = """
SELECT
    COUNT(OrderID) AS TotalOrders,
    SUM(Quantity) AS TotalUnitsSold,
    ROUND(SUM(TotalPrice), 2) AS TotalRevenue,
    ROUND(AVG(TotalPrice), 2) AS AvgOrderValue
FROM orders;
"""

pd.read_sql_query(query_2, conn)

   TotalOrders  TotalUnitsSold  TotalRevenue  AvgOrderValue
0         1200            3535    1264761.96        1053.97

Step # 5: Filtering High-Value Orders (Where & Order By)

In [12]:
query_3 = """
SELECT OrderID, CustomerID, Product, Quantity, TotalPrice, OrderStatus
FROM orders
WHERE TotalPrice > 2500 AND OrderStatus = 'Delivered'
ORDER BY TotalPrice DESC
LIMIT 10;
"""

pd.read_sql_query(query_3, conn)

     OrderID CustomerID  Product  Quantity  TotalPrice OrderStatus
0  ORD200789     C57276   Tablet         5     3456.40   Delivered
1  ORD200632     C67260   Laptop         5     3390.80   Delivered
2  ORD201065     C47778  Printer         5     3334.00   Delivered
3  ORD200361     C53464  Printer         5     3299.25   Delivered
4  ORD200837     C88029    Chair         5     3277.75   Delivered
5  ORD201079     C89979    Phone         5     3170.00   Delivered
6  ORD200511     C11415  Monitor         5     2876.20   Delivered
7  ORD200578     C50415  Monitor         5     2830.35   Delivered
8  ORD200883     C43595  Printer         5     2807.40   Delivered
9  ORD200769     C13366  Printer         4     2714.20   Delivered

Step # 6: Product Performance Analysis (Group By & Aggregations)

In [14]:
query_4 = """
SELECT
    Product,
    COUNT(OrderID) AS TotalOrders,
    SUM(Quantity) AS TotalUnitsSold,
    ROUND(SUM(TotalPrice), 2) AS TotalRevenue,
    ROUND(AVG(TotalPrice), 2) AS AvgUnitPrice
FROM orders
GROUP BY Product
ORDER BY TotalRevenue DESC;
"""

pd.read_sql_query(query_4, conn)

   Product  TotalOrders  TotalUnitsSold  TotalRevenue  AvgUnitPrice
0    Chair          178             562     195620.11       1098.99
1  Printer          181             542     195612.61       1080.73
2   Laptop          173             535     192126.56       1110.56
3   Tablet          179             497     186568.95       1042.28
4  Monitor          163             480     175651.41       1077.62
5     Desk          170             508     167459.93        985.06
6    Phone          156             411     151722.39        972.58

Step # 7: Order Status Breakdown (Group By & Count)

In [17]:
query_5 = """
SELECT
  OrderStatus,
  COUNT(OrderID) AS OrderCount,
  ROUND(SUM(TotalPrice), 2) AS TotalRevenue
FROM orders
GROUP BY OrderStatus
ORDER BY OrderCount DESC;
"""

pd.read_sql_query(query_5, conn)

  OrderStatus  OrderCount  TotalRevenue
0   Cancelled         250     276396.21
1    Returned         247     243277.70
2     Pending         237     256328.15
3     Shipped         235     246159.58
4   Delivered         231     242600.32

Step # 8: Payment Method Usage & Average Spend

In [19]:
query_6 = """
SELECT
  PaymentMethod,
  COUNT(OrderID) AS TotalTransactions,
  ROUND(AVG(TotalPrice), 2) AS AvgSpendPerOrder,
  ROUND(SUM(TotalPrice), 2) AS TotalSpend
FROM orders
GROUP BY PaymentMethod
ORDER BY TotalTransactions DESC;
"""

pd.read_sql_query(query_6, conn)

  PaymentMethod  TotalTransactions  AvgSpendPerOrder  TotalSpend
0        Online                258           1017.22   262442.94
1          Cash                246           1056.04   259786.29
2   Credit Card                234           1127.55   263847.63
3    Debit Card                232           1001.56   232361.18
4     Gift Card                230           1070.97   246323.92

Step # 9: Marketing Channel / Referal Source Performance

In [22]:
query_7 = """
SELECT
    ReferralSource,
    COUNT(OrderID) AS OrderCount,
    ROUND(SUM(TotalPrice), 2) AS TotalRevenueGenerated
FROM orders
GROUP BY ReferralSource
ORDER BY TotalRevenueGenerated DESC;
"""

pd.read_sql_query(query_7, conn)

  ReferralSource  OrderCount  TotalRevenueGenerated
0      Instagram         259              275285.45
1          Email         250              261808.55
2         Google         241              250441.48
3       Facebook         228              250410.90
4       Referral         222              226815.58

Step # 10: Close Connection

In [24]:
conn.close()
print("Database connection closed. SQL Analysis completed successfully.")

Database connection closed. SQL Analysis completed successfully.